host: "localhost"
port: 11000
scheme: "http"
servers:
  - name: "Server P"
    scheme: "http"
    host: "localhost"
    port: 11001
    connections: 2000
    
  - name: "Server Q"
    scheme: "http"
    host: "localhost"
    port: 11002
    connections: 2000

  - name: "Server R"
    scheme: "http"
    host: "localhost"
    port: 11003
    connections: 2000

  - name: "Server S"
    scheme: "http"
    host: "localhost"
    port: 11004
    connections: 2000
    
  - name: "Server T"
    scheme: "http"
    host: "localhost"
    port: 11005
    connections: 2000

 