host: "localhost"
port: 8000
scheme: "http"
servers:
  - name: "Server A"
    scheme: "http"
    host: "localhost"
    port: 8001
    connections: 2000
    
  - name: "Server B"
    scheme: "http"
    host: "localhost"
    port: 8002
    connections: 2000

  - name: "Server C"
    scheme: "http"
    host: "localhost"
    port: 8003
    connections: 2000

  - name: "Server D"
    scheme: "http"
    host: "localhost"
    port: 8004
    connections: 2000
    
  - name: "Server E"
    scheme: "http"
    host: "localhost"
    port: 8005
    connections: 2000

 