host: "localhost"
port: 9000
scheme: "http"
servers:
  - name: "Server F"
    scheme: "http"
    host: "localhost"
    port: 9001
    connections: 2000
    
  - name: "Server G"
    scheme: "http"
    host: "localhost"
    port: 9002
    connections: 2000

  - name: "Server H"
    scheme: "http"
    host: "localhost"
    port: 9003
    connections: 2000

  - name: "Server I"
    scheme: "http"
    host: "localhost"
    port: 9004
    connections: 2000
    
  - name: "Server J"
    scheme: "http"
    host: "localhost"
    port: 9005
    connections: 20000

 